# Build arguments
ARG SOURCE_CODE=.

FROM registry.access.redhat.com/ubi9/go-toolset:1.24@sha256:6234f572204d672a0ee0686d748fbb9b7b05679368bf0d7a4446e13970e58060 as builder

ARG SOURCE_CODE
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY main.go main.go
COPY api/ api/
COPY controllers/ controllers/
COPY config/internal config/internal

USER root
# Build
RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} GO111MODULE=on GOEXPERIMENT=strictfipsruntime go build -tags strictfipsruntime -a -o manager main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:759f5f42d9d6ce2a705e290b7fc549e2d2cd39312c4fa345f93c02e4abb8da95 AS runtime

## Build args to be used at this step
ARG USER=65532

LABEL com.redhat.component="odh-data-science-pipelines-operator-controller-container" \
      name="managed-open-data-hub/odh-data-science-pipelines-operator-controller-rhel8" \
      description="Manages lifecycle of Data Science Pipelines Custom Resources and associated Kubernetes resources" \
      summary="odh-data-science-pipelines-operator-controller" \
      maintainer="['managed-open-data-hub@redhat.com']" \
      io.openshift.expose-services="" \
      io.k8s.display-name="data-science-pipelines-operator-controller" \
      io.k8s.description="data-science-pipelines-operator-controller" \
      com.redhat.license_terms="https://www.redhat.com/licenses/Red_Hat_Standard_EULA_20191108.pdf"

WORKDIR /
COPY --from=builder /workspace/manager .
COPY --from=builder /workspace/config/internal ./config/internal

## Create a non-root user with UID 65532 and switch to it
USER ${USER}:${USER}

ENTRYPOINT ["/manager"]
